default:
    trainer: ppo
    buffer_size: 4096
    batch_size: 2048
    beta: 5.0e-3
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

Ball:
    num_layers: 1
    learning_rate: 3.0e-3
    max_steps: 3e5
    
Hunter:
    learning_rate: 2.0e-3
    max_steps: 1.5e6
    time_horizon: 128
    
Hunted:
    learning_rate: 2.0e-3
    max_steps: 0.75e6
    time_horizon: 128
  
VolleyballPlayer:
    max_steps: 1e6
    batch_size: 128
    learning_rate: 1.0e-3
    hidden_units: 128
    
TicTacPlayer:
    time_horizon: 128
    buffer_size: 1024
    batch_size: 256
    summary_freq: 300
    num_layers: 3
    max_steps: 3.0e5