default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
BallBrain:
    buffer_size: 1000
    batch_size: 10
HuntedBrain:
    buffer_size: 5000
    batch_size: 100
HunterBrain:
    buffer_size: 5000
    batch_size: 100
VolleyballBrain:
    buffer_size: 1000
    batch_size: 100
TicTacBrain:
    learning_rate: 6.0e-5
    buffer_size: 1000
    batch_size: 100
    num_layers: 3
    hidden_units: 256
    beta: 0.5e-2